import { LightningElement } from 'lwc';

export default class HelloExpression extends LightningElement {
    greetMessage="Welcome to LWC";  //Field or property in camel case

    handleChange(event)
    {
       /*  alert("Event generated by "+ event.target.name);
        alert("value in text box is.."+event.target.value); */
        //Whenever refer any property of class in a function use this.propertyName
        this.greetMessage=event.target.value;

    }
}